version: '2'

services:
  app:
    image: 'api-paiement:latest'
    ports:
      - 8080:8080
    build:
      context: .
    container_name: api-paiement
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tpiapipaiment
      - SPRING_DATASOURCE_USERNAME=tpiapipaiment
      - SPRING_DATASOURCE_PASSWORD=tpiapipaiment
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - 5432:5432
    container_name: db
    environment:
      - POSTGRES_USER=tpiapipaiment
      - POSTGRES_PASSWORD=tpiapipaiment